apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-docker-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: aws-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-docker
  template:
    metadata:
      labels:
        app: aws-docker
    spec:
      containers:
        - name: aws-docker-container
          image: akshithanandre/aws-docker-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"

