apiVersion: v1
kind: Service
metadata:
  name: aws-docker-service
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: aws-docker
  ports:
    - name: http
      port: 8081
      targetPort: 8080
